export const SELECTED_FACTORY_NAME = 'SELECTED_FACTORY_NAME';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_PWD = 'SET_USER_PWD';
export const SET_SELECTED_FACTORY = 'SET_SELECTED_FACTORY';